version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:8.0-node-browsers

    steps:
      - checkout

      # PHP extension dependencies
      - run:
          name: Install PHP extensions
          command: |
            sudo apt-get update
            sudo apt-get install -y libzip-dev zip unzip
            sudo docker-php-ext-install pdo_mysql zip

      # Install composer dependencies
      - run:
          name: Install Composer dependencies
          command: composer install --no-dev --optimize-autoloader --no-interaction

      # Environment setup
      - run:
          name: Environment setup
          command: cp .env.example .env
          
      # Generate application key
      - run:
          name: Generate application key
          command: php artisan key:generate

      # Run database migrations
      - run:
          name: Database migrations
          command: php artisan migrate --force

  deploy:
    docker:
      - image: circleci/php:8.0-node-browsers

    steps:
      - checkout

      # SSH key setup
      - add_ssh_keys:
          fingerprints:
            - "YOUR_SSH_KEY_FINGERPRINT" # Replace with your SSH key fingerprint

      # Add Google Chrome repository key using gpg
      - run:
          name: Add Google Chrome repository key
          command: |
            curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-linux-signing-key.gpg

      # Set up Google Chrome repository
      - run:
          name: Set up Google Chrome repository
          command: |
            echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux-signing-key.gpg] https://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list

      # Update repository information
      - run:
          name: Update repositories
          command: sudo apt-get update

      # Deploy to EC2
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no ec2-user@ec2-18-177-136-195.ap-northeast-1.compute.amazonaws.com "cd /var/www/html && git pull origin master && composer install --no-dev --optimize-autoloader --no-interaction && php artisan migrate --force"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
