version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:8.0-apache
      - image: circleci/mysql:5.7
    steps:
      - checkout
      - run:
          name: Install MySQL and PHP extensions
          command: |
            sudo apt-get update
            sudo apt-get install -y default-mysql-client libmariadb-dev
            sudo docker-php-ext-install pdo_mysql

      - run:
          name: Install gd extension and dependencies
          command: |
            sudo apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev
            sudo docker-php-ext-configure gd --with-jpeg --with-freetype
            sudo docker-php-ext-install gd

      - run:
          name: Install dependencies, configure environment, and run tests
          command: |
            cd src
            composer install --no-interaction --prefer-dist --optimize-autoloader
            cp .env.example .env.testing
            php artisan key:generate --ansi --env=testing
            sed -i "s/DB_CONNECTION=.*/DB_CONNECTION=mysql/" .env.testing
            sed -i "s/DB_HOST=.*/DB_HOST=mysql/" .env.testing
            sed -i "s/DB_DATABASE=.*/DB_DATABASE=demo_test/" .env.testing
            sed -i "s/DB_USERNAME=.*/DB_USERNAME=root/" .env.testing
            sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=root/" .env.testing
            echo "Current environment settings:"
            cat .env.testing
            php artisan config:clear --env=testing
            php artisan migrate:fresh --seed --force --env=testing
            vendor/bin/phpunit

  deploy:
    docker:
      - image: circleci/php:8.0
    steps:
      - checkout
      - run:
          name: Add SSH key
          command: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H ec2-18-181-249-51.ap-northeast-1.compute.amazonaws.com >> ~/.ssh/known_hosts
      - run:
          name: Deploy over SSH
          command: |
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@ec2-18-181-249-51.ap-northeast-1.compute.amazonaws.com "\
            cd /var/www/shop-laravel && \
            git fetch origin && \
            git reset --hard origin/main && \
            cd src && \
            composer install --no-interaction --prefer-dist --optimize-autoloader && \
            cp env/.env.prod .env && \
            php artisan cache:clear && \
            php artisan config:clear && \
            php artisan route:clear && \
            php artisan view:clear && \
            php artisan optimize:clear && \
            php artisan event:clear && \
            php artisan migrate --force"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
