version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Install dependencies and PHP extensions
          command: |
            sudo apt-get update
            sudo apt-get install -y libzip-dev zip unzip
            docker-php-ext-configure zip
            docker-php-ext-install zip

      - run:
          name: Install Composer dependencies
          command: |
            composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - run:
          name: Prepare environment
          command: |
            cp .env.example .env
            php artisan key:generate
            php artisan migrate --seed

      - run:
          name: Run tests
          command: |
            vendor/bin/phpunit --coverage-text --colors=never

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
