version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:8.0-apache
    steps:
      - checkout

      # 環境変数の設定
      - run:
          name: Set Environment Variables
          command: |
            echo 'DB_CONNECTION=mysql' >> ~/.bashrc
            echo 'DB_HOST=database-1.cjua0qayaefc.ap-northeast-1.rds.amazonaws.com' >> ~/.bashrc
            echo 'DB_PORT=3306' >> ~/.bashrc
            echo 'DB_DATABASE=laravel_db' >> ~/.bashrc
            echo 'DB_USERNAME=admin' >> ~/.bashrc
            echo 'DB_PASSWORD=segnIg-cukqih-koqpi9' >> ~/.bashrc
            source ~/.bashrc

      # MySQLクライアントのインストール
      - run:
          name: Install MySQL client
          command: |
            sudo apt-get update
            sudo apt-get install -y default-mysql-client

      # MySQL接続のテスト
      - run:
          name: Test MySQL connection
          command: |
            mysql -h $DB_HOST -u $DB_USERNAME -p$DB_PASSWORD -e "SHOW DATABASES;"

      # PHP MySQL拡張のインストール
      - run:
          name: Install PHP MySQL extension
          command: |
            sudo apt-get install -y libmariadb-dev
            sudo docker-php-ext-install pdo_mysql

      # 依存関係のインストールとテストの実行
      - run:
          name: Install dependencies and run tests
          command: |
            cd src
            composer install --no-interaction --prefer-dist --optimize-autoloader
            cp .env.example .env
            php artisan key:generate --ansi
            php artisan config:cache
            php artisan migrate:fresh --seed --force
            vendor/bin/phpunit

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
