version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:8.0-apache
        environment:
          PHP_EXTENSIONS: gd # GD拡張機能を有効にする
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: demo_test
          DB_USERNAME: root
          DB_PASSWORD: root

    steps:
      - checkout

      # Install dependencies including libpng
      - run:
          name: Install dependencies including libpng
          command: |
            sudo apt-get update
            sudo apt-get install -y default-mysql-client libmariadb-dev libpng-dev # libpng-devを追加

      # Install PHP extensions including GD
      - run:
          name: Install PHP extensions including GD
          command: |
            sudo docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp --with-xpm --with-png-dir=/usr/include/
            sudo docker-php-ext-install -j$(nproc) gd

      # Install PHP PDO MySQL extension
      - run:
          name: Install PHP PDO MySQL extension
          command: |
            sudo docker-php-ext-install pdo_mysql


      # Install dependencies, configure environment, and run tests
      - run:
          name: Install dependencies, configure environment, and run tests
          command: |
            cd src
            composer install --no-interaction --prefer-dist --optimize-autoloader
            cp .env.example .env.testing
            php artisan key:generate --ansi --env=testing

            # Update database configuration in .env.testing
            sed -i "s/DB_CONNECTION=.*/DB_CONNECTION=mysql/" .env.testing
            sed -i "s/DB_HOST=.*/DB_HOST=mysql/" .env.testing
            sed -i "s/DB_DATABASE=.*/DB_DATABASE=demo_test/" .env.testing
            sed -i "s/DB_USERNAME=.*/DB_USERNAME=root/" .env.testing
            sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=root/" .env.testing

            # Output current environment settings for debug
            echo "Current environment settings:"
            cat .env.testing

            # Clear configuration cache, test MySQL connection, run migrations and tests
            php artisan config:clear --env=testing
            php artisan migrate:fresh --seed --force --env=testing
            vendor/bin/phpunit

  deploy:
    docker:
      - image: circleci/php:8.0
    steps:
      - checkout

      # Add SSH keys for deployment
      - add_ssh_keys:
          fingerprints:
            - "TO+Duj/pL4QtNcadDHvGzcttWG8nB462D5+GzIzlC+Y"

      # Deploy over SSH
      - run:
          name: Deploy over SSH
          command: |
            ssh -o StrictHostKeyChecking=no \
                -i ~/.ssh/shop-caravel.pem \
                ec2-user@ec2-43-207-83-43 "\
                cd /var/www/shop-laravel && \
                git pull origin master && \
                cd src && \
                composer install --no-interaction --prefer-dist --optimize-autoloader && \
                php artisan migrate --force"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
