version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      
      # Composerのアップグレードと設定
      - run:
          name: Upgrade to Composer 2
          command: |
            sudo composer self-update --2
      
      # Composerのキャッシュを復元
      - restore_cache:
          key: composer-v1-{{ checksum "composer.json" }}
      
      # Composerの依存関係をインストール
      - run: composer install -n --prefer-dist
      
      # Composerのキャッシュを保存
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      
      # npmのキャッシュを復元
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
      
      # npmの依存関係をインストール
      - run:
          name: Install npm dependencies
          command: |
            npm ci
            
      # npmのキャッシュを保存
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      
      # npmのビルド
      - run: npm run dev
      
      # PHPUnitの実行
      - run:
          name: Run PHPUnit tests
          command: vendor/bin/phpunit
