version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:8.0-node
    steps:
      - checkout
      - run:
          name: Install PHP extensions
          command: |
            sudo apt-get update && sudo apt-get install -y \
            php8.0-bcmath php8.0-xml php8.0-mbstring php8.0-gd

      # Install dependencies
      - run:
          name: Install Composer dependencies
          command: composer install --no-interaction --prefer-dist --optimize-autoloader

      # Install PHPUnit
      - run:
          name: Install PHPUnit
          command: composer require --dev phpunit/phpunit

      # Run PHPUnit tests
      - run:
          name: Run PHPUnit tests
          command: vendor/bin/phpunit

  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "TO+Duj/pL4QtNcadDHvGzcttWG8nB462D5+GzIzlC+Y"
      - run:
          name: Deploy Over SSH
          command: |
            ssh -o StrictHostKeyChecking=no \
                -i ~/.ssh/shop-caravel.pem \
                ec2-user@ec2-43-207-83-43 \
                "cd /var/www/shop-laravel && \
                git pull origin master && \
                composer install --no-interaction --prefer-dist --optimize-autoloader && \
                php artisan migrate --force"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
