version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:8.0-node-browsers
      - image: circleci/mysql:5.7
        name: mysql
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_db

    steps:
      - checkout

      # Add Google Chrome repository key using gpg
      - run:
          name: Add Google Chrome repository key
          command: |
            curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-linux-signing-key.gpg

      # Set up Google Chrome repository
      - run:
          name: Set up Google Chrome repository
          command: |
            echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux-signing-key.gpg] https://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list

      # PHP extension dependencies
      - run:
          name: Install PHP extensions and MySQL client
          command: |
            sudo apt-get update
            sudo apt-get install -y libzip-dev zip unzip default-mysql-client
            sudo docker-php-ext-install pdo_mysql zip

      # Install Composer dependencies
      - run:
          name: Install Composer dependencies
          command: |
            cd /home/circleci/project/src
            composer install --no-dev --optimize-autoloader --no-interaction

      # Environment setup for testing
      - run:
          name: Environment setup for testing
          command: |
            cd /home/circleci/project/src
            cp .env.example .env
            php artisan key:generate

      # Wait for MySQL to be ready
      - run:
          name: Wait for MySQL
          command: |
            for i in `seq 1 30`; do nc -z mysql 3306 && break; sleep 1; done

      # Setup MySQL user and permissions
      - run:
          name: Setup MySQL user and permissions
          command: |
            mysql -h mysql -uroot -proot -e "CREATE USER 'laravel_user'@'%' IDENTIFIED BY 'laravel_pass';"
            mysql -h mysql -uroot -proot -e "GRANT ALL PRIVILEGES ON laravel_db.* TO 'laravel_user'@'%';"
            mysql -h mysql -uroot -proot -e "FLUSH PRIVILEGES;"

      # Database setup
      - run:
          name: Database setup
          command: |
            cd /home/circleci/project/src
            php artisan migrate --force

      # Run tests
      - run:
          name: Run tests
          command: |
            cd /home/circleci/project/src
            php artisan test

  deploy:
    docker:
      - image: circleci/php:8.0-node-browsers

    steps:
      - checkout

      # SSH key setup
      - add_ssh_keys:
          fingerprints:
            - "YOUR_SSH_KEY_FINGERPRINT" # Replace with your SSH key fingerprint

      # Add Google Chrome repository key using gpg
      - run:
          name: Add Google Chrome repository key
          command: |
            curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-linux-signing-key.gpg

      # Set up Google Chrome repository
      - run:
          name: Set up Google Chrome repository
          command: |
            echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux-signing-key.gpg] https://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list

      # Update repository information
      - run:
          name: Update repositories
          command: sudo apt-get update

      # Deploy to EC2
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no ec2-user@ec2-57-180-65-218.ap-northeast-1.compute.amazonaws.com "cd /var/www/html && git pull origin master && cp .env.deploy .env && composer install --no-dev --optimize-autoloader --no-interaction && php artisan migrate --force"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
