version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:8.0-apache
        environment:
          PHP_EXTENSIONS: gd
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: demo_test
          DB_USERNAME: root
          DB_PASSWORD: root
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: demo_test

    steps:
      - checkout

      # Install MySQL client and PHP PDO MySQL extension
      - run:
          name: Install MySQL and PHP extensions
          command: |
            sudo apt-get update
            sudo apt-get install -y default-mysql-client libmariadb-dev
            sudo docker-php-ext-install pdo_mysql

      # Install gd extension and dependencies
      - run:
          name: Install gd extension and dependencies
          command: |
            sudo apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev
            sudo docker-php-ext-configure gd --with-jpeg --with-freetype
            sudo docker-php-ext-install gd

      # Install dependencies, configure environment, and run tests
      - run:
          name: Install dependencies, configure environment, and run tests
          command: |
            cd src
            composer install --no-interaction --prefer-dist --optimize-autoloader
            cp .env.example .env.testing
            php artisan key:generate --ansi --env=testing

            # Update database configuration in .env.testing
            sed -i "s/DB_CONNECTION=.*/DB_CONNECTION=mysql/" .env.testing
            sed -i "s/DB_HOST=.*/DB_HOST=mysql/" .env.testing
            sed -i "s/DB_DATABASE=.*/DB_DATABASE=demo_test/" .env.testing
            sed -i "s/DB_USERNAME=.*/DB_USERNAME=root/" .env.testing
            sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=root/" .env.testing

            # Output current environment settings for debug
            echo "Current environment settings:"
            cat .env.testing

            # Clear configuration cache, test MySQL connection, run migrations and tests
            php artisan config:clear --env=testing
            php artisan migrate:fresh --seed --force --env=testing
            vendor/bin/phpunit

  deploy:
    docker:
      - image: circleci/php:8.0

    steps:
      - checkout

      # SSHキーを追加（手動で追加）
      - add_ssh_keys:
          fingerprints:
            - "TO+Duj/pL4QtNcadDHvGzcttWG8nB462D5+GzIzlC+Y"

      # SSHキーの場所を環境変数にセット
      - run:
          name: Setup SSH key path
          command: echo 'export SSH_KEY_PATH=/home/circleci/.ssh/shop-caravel.pem' >> $BASH_ENV

      # SSH経由でデプロイ
      - run:
          name: Deploy over SSH
          command: |
            ssh -i $SSH_KEY_PATH \
                ec2-user@ec2-43-207-83-43.ap-northeast-1.compute.amazonaws.com "\
                cd /var/www/shop-laravel && \
                git pull origin master && \
                cd src && \
                composer install --no-interaction --prefer-dist --optimize-autoloader && \
                php artisan migrate --force"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build