version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/php:8.0-node-browsers

    steps:
      - checkout

      # Install dependencies, build assets, run tests (if needed)

      - run:
          name: Deploy to EC2
          command: |
            ssh -i "shop-caravel.pem" ec2-user@ec2-18-177-136-195.ap-northeast-1.compute.amazonaws.com "cd /var/www/html && git pull origin master && composer install --no-dev && php artisan migrate --force"

workflows:
  version: 2
  deploy:
    jobs:
      - deploy
