version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout

      # Composerのバージョンアップデート
      - run: sudo composer self-update --2

      # composer.jsonが存在しない場合にのみ実行
      - run:
          name: Initialize composer.json
          command: |
            if [ ! -f composer.json ]; then
              composer init
            fi

      # Composerの依存関係をインストール
      - restore_cache:
          key: composer-v2-{{ checksum "composer.json" }}
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v2-{{ checksum "composer.json" }}
          paths:
            - vendor

      # npmの依存関係をインストール
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
      - run: npm install

      # npm ciを実行
      - run: npm ci

      # npm run devを実行
      - run: npm run dev

      # PHPUnitでテストを実行
      - run:
          name: php test
          command: vendor/bin/phpunit
