version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4-node  # PHP 7.4とNode.jsを使用するDockerイメージ
    working_directory: /test/second-laravel/src  # 作業ディレクトリを指定
    steps:
      - checkout  # リポジトリをチェックアウトするステップ
      - run:
          name: Install dependencies
          command: |
            composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - run:
          name: Run tests
          command: |
            phpunit

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
