version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    working_directory: ~/shop-laravel/src

    steps:
      - checkout

      # Google ChromeのGPGキーを追加
      - run:
          name: Add Google Chrome GPG Key
          command: |
            curl -sSL https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -

      # 依存関係とPHP拡張機能のインストール
      - run:
          name: Install Dependencies and PHP Extensions
          command: |
            sudo apt-get update
            sudo apt-get install -y libzip-dev zip unzip
            sudo docker-php-ext-configure zip
            sudo docker-php-ext-install zip

      # composer.jsonの存在確認と初期化
      - run:
          name: Check for composer.json and Initialize if not exists
          command: |
            if [ ! -f composer.json ]; then
              composer init --name="your-vendor-name/your-package-name" --stability=dev --license=MIT --no-interaction
            fi

      # Composerの依存関係をインストール
      - run:
          name: Install Composer Dependencies
          command: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      # vendor/binディレクトリの内容を確認
      - run:
          name: Check contents of vendor/bin
          command: ls -al vendor/bin

      # 現在のディレクトリのファイル一覧を表示
      - run:
          name: List files in current directory
          command: ls -al

      # 環境を準備する
      - run:
          name: Prepare Environment
          command: |
            cp .env.example .env
            php artisan key:generate
            php artisan migrate --seed

      # zip拡張機能をビルドしてインストール
      - run:
          name: Build and install zip extension
          command: |
            sudo apt-get install -y libzip-dev
            sudo pecl channel-update pecl.php.net
            sudo pecl install zip
            echo "extension=zip.so" | sudo tee -a /usr/local/etc/php/conf.d/docker-php-ext-zip.ini

      # テストを実行
      - run:
          name: Run Tests
          command: vendor/bin/phpunit --coverage-text --colors=never

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
