version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4-node
    working_directory: /var/www/shop-laravel  # プロジェクトのルートディレクトリに修正
    steps:
      - run:
          name: Create directory and set permissions
          command: |
            sudo mkdir -p /var/www/shop-laravel
            sudo chown -R circleci:circleci /var/www/shop-laravel
            sudo chmod -R 777 /var/www/shop-laravel

      - checkout

      - run:
          name: Install dependencies
          command: |
            cd /var/www/shop-laravel
            composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - run:
          name: Run tests
          command: |
            phpunit

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
