version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4-node
    working_directory: /var/www/shop-laravel  # プロジェクトの実際のパスに修正
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - run:
          name: Run tests
          command: |
            phpunit

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
