version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:8.0-node
    steps:
      - checkout

      # Install PHP 8.0 and extensions using Homebrew
      - run:
          name: Install PHP 8.0 and extensions using Homebrew
          command: |
            brew update
            brew install php@8.0
            brew install php@8.0-bcmath php@8.0-xml php@8.0-mbstring

      # Install Composer dependencies
      - run:
          name: Install Composer dependencies
          command: composer install --no-interaction --prefer-dist --optimize-autoloader

      # Install PHPUnit
      - run:
          name: Install PHPUnit
          command: composer require --dev phpunit/phpunit

      # Run PHPUnit tests
      - run:
          name: Run PHPUnit tests
          command: vendor/bin/phpunit

  deploy:
    docker:
      - image: circleci/php:8.0-node
    steps:
      - checkout

      # Add SSH keys for deployment
      - add_ssh_keys:
          fingerprints:
            - "TO+Duj/pL4QtNcadDHvGzcttWG8nB462D5+GzIzlC+Y"

      # Deploy over SSH
      - run:
          name: Deploy Over SSH
          command: |
            ssh -o StrictHostKeyChecking=no \
                -i ~/.ssh/shop-caravel.pem \
                ec2-user@ec2-43-207-83-43 "\
                cd /var/www/shop-laravel && \
                git pull origin master && \
                composer install --no-interaction --prefer-dist --optimize-autoloader && \
                php artisan migrate --force"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
