version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4
        environment:
          MYSQL_ROOT_PASSWORD: root  # MySQLのルートパスワードを設定する
          MYSQL_DATABASE: demo_test  # テスト用のデータベース名を設定する
    steps:
      - checkout

      # Install PHP and MySQL PDO driver
      - run:
          name: Install PHP and MySQL PDO driver
          command: |
            sudo apt-get update
            sudo apt-get install -y php7.4-common php7.4-mysql

      # Install dependencies and run tests
      - run:
          name: Install dependencies and run tests
          command: |
            cd src  # srcディレクトリに移動する
            composer install --no-interaction --prefer-dist --optimize-autoloader
            cp .env.example .env  # .envファイルのコピー（必要に応じて）

            # Laravelアプリケーションのセットアップ
            php artisan key:generate --ansi
            php artisan config:cache
            php artisan migrate:fresh --seed --force  # テスト用データベースのリフレッシュ

            vendor/bin/phpunit

  deploy:
    docker:
      - image: circleci/php:7.4
    steps:
      - checkout

      # Add SSH keys for deployment
      - add_ssh_keys:
          fingerprints:
            - "TO+Duj/pL4QtNcadDHvGzcttWG8nB462D5+GzIzlC+Y"

      # Deploy over SSH
      - run:
          name: Deploy over SSH
          command: |
            ssh -o StrictHostKeyChecking=no \
                -i ~/.ssh/shop-caravel.pem \
                ec2-user@ec2-43-207-83-43 "\
                cd /var/www/shop-laravel && \
                git pull origin master && \
                cd src && \
                composer install --no-interaction --prefer-dist --optimize-autoloader && \
                php artisan migrate --force"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
