version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:8.0-apache
        environment:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel_db
          DB_USERNAME: laravel_user
          DB_PASSWORD: laravel_pass
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: laravel_db
          MYSQL_USER: laravel_user
          MYSQL_PASSWORD: laravel_pass

    steps:
      - checkout

      # Wait for MySQL to be ready
      - run:
          name: Waiting for MySQL to be ready
          command: |
            dockerize -wait tcp://localhost:3306 -timeout 1m

      # Install MySQL client and PHP PDO MySQL extension
      - run:
          name: Install MySQL and PHP extensions
          command: |
            sudo apt-get update
            sudo apt-get install -y default-mysql-client libmariadb-dev
            sudo docker-php-ext-install pdo_mysql

      # Install dependencies, configure environment, and run tests
      - run:
          name: Install dependencies, configure environment, and run tests
          command: |
            cd src
            composer install --no-interaction --prefer-dist --optimize-autoloader
            cp .env.example .env

            # Update database configuration in .env
            sed -i "s/DB_HOST=.*/DB_HOST=127.0.0.1/" .env
            sed -i "s/DB_DATABASE=.*/DB_DATABASE=${DB_DATABASE}/" .env
            sed -i "s/DB_USERNAME=.*/DB_USERNAME=${DB_USERNAME}/" .env
            sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=${DB_PASSWORD}/" .env

            # Output current environment settings for debug
            echo "Current environment settings:"
            cat .env

            # Clear configuration cache, test MySQL connection, run migrations and tests
            php artisan config:clear
            php artisan migrate:fresh --seed --force
            vendor/bin/phpunit

  deploy:
    docker:
      - image: circleci/php:8.0
    steps:
      - checkout

      # Add SSH keys for deployment
      - add_ssh_keys:
          fingerprints:
            - "TO+Duj/pL4QtNcadDHvGzcttWG8nB462D5+GzIzlC+Y"

      # Deploy over SSH
      - run:
          name: Deploy over SSH
          command: |
            ssh -o StrictHostKeyChecking=no \
                -i ~/.ssh/shop-caravel.pem \
                ec2-user@ec2-43-207-83-43 "\
                cd /var/www/shop-laravel && \
                git pull origin master && \
                cd src && \
                composer install --no-interaction --prefer-dist --optimize-autoloader && \
                php artisan migrate --force"

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
